name: unit
on: pull_request
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: |
        go mod download

    - name: unit
      run: |
        go test ./go/...
